name: Npm Publish
on: [workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./apps/chart
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: npm install
        run: |
          npm install
      - name: npm install(toast.ui-chart)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm install
      - name: eslint
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run lint
  types:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./apps/chart
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: npm install
        run: |
          npm install
      - name: npm install(toast.ui-chart)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm install
      - name: check types
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run check-types
  test:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./apps/chart
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: npm install
        run: |
          npm install
      - name: npm install(toast.ui-chart)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm install
      - name: test
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run test

  publish:
    runs-on: ubuntu-latest
    needs: [lint, types, test]
    steps:
      - uses: actions/checkout@v2
      - name: Check the package version
        id: check
        uses: PostHog/check-package-version@v2
        with:
          path: ./apps/chart
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Create Tag
        run: |
          git config --local user.email 'jw.lee@nhn.com'
          git config --local user.name 'jwlee1108'
          git tag v${{ steps.check.outputs.committed-version }}
      - name: Push Tag
        run: |
          git push origin v${{ steps.check.outputs.committed-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Npm Publish(chart)
        working-directory: ./apps/chart
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
