name: Npm Publish
on: [workflow_dispatch]
env:
  WORKING_DIRECTORY: ./apps/chart
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: npm install
        run: |
          npm install
      - name: npm install (toast.ui-chart)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm install
      - name: eslint
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run lint
  types:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./apps/chart
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: npm install
        run: |
          npm install
      - name: npm install (toast.ui-chart)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm install
      - name: check types
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run check-types
  test:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./apps/chart
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: npm install
        run: |
          npm install
      - name: npm install (toast.ui-chart)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm install
      - name: test
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run test
          
  check-version:
    name: Check package version
    needs: [lint, types, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          registry-url: https://registry.npmjs.org/
      - name: Check package version
        id: check
        uses: PostHog/check-package-version@v2
        with:
          path: ${{ env.WORKING_DIRECTORY }}/
      - name: Log when unchanged
        if: steps.check.outputs.is-new-version == 'false'
        run: 'echo "No version change"'
      - name: Cancel Workflow
        if: steps.check.outputs.is-new-version == 'false'
        uses: andymckay/cancel-action@0.2
